import Pelle.ColorePelle;

void main() throws Exception {
    Personaggio[] personaggi = new Personaggio[24];
    Personaggio p1 = new Personaggio(ColoriCapelli.BIONDI,ColoriOcchi.AZZURRI, ColorePelle.CHIARA,false,false,false,false,false,false,false,false,false,"Immagini/Giocatori/1.png","Anita");
    Personaggio p2 = new Personaggio(ColoriCapelli.BIANCHI,ColoriOcchi.MARRONI, ColorePelle.CHIARA,false,false,true,true,false,false,false,false,false,"Immagini/Giocatori/2.png","Anne");
    Personaggio p3 = new Personaggio(ColoriCapelli.CASTANI,ColoriOcchi.MARRONI, ColorePelle.SCURA,false,false,false,false,true,false,false,true,false,"Immagini/Giocatori/3.png","Bernard");
    Personaggio p4 = new Personaggio(ColoriCapelli.CASTANI,ColoriOcchi.MARRONI, ColorePelle.SCURA,false,false,false,false,false,true,false,false,false,"Immagini/Giocatori/4.png","Carmen");
    Personaggio p5 = new Personaggio(ColoriCapelli.NESSUNO,ColoriOcchi.MARRONI, ColorePelle.CHIARA,false,true,false,true,true,false,false,false,true,"Immagini/Giocatori/5.png","Charles");
    Personaggio p6 = new Personaggio(ColoriCapelli.NESSUNO,ColoriOcchi.AZZURRI, ColorePelle.CHIARA,false,false,false,true,true,false,false,false,true,"Immagini/Giocatori/6.png","Daniel");
    Personaggio p7 = new Personaggio(ColoriCapelli.BIONDI,ColoriOcchi.MARRONI, ColorePelle.CHIARA,false,false,false,false,true,false,false,false,false,"Immagini/Giocatori/7.png","Eric");
    Personaggio p8 = new Personaggio(ColoriCapelli.NERI,ColoriOcchi.MARRONI, ColorePelle.CHIARA,false,false,false,false,true,false,false,true,false,"Immagini/Giocatori/8.png","Frank");
    Personaggio p9 = new Personaggio(ColoriCapelli.BIONDI,ColoriOcchi.MARRONI, ColorePelle.CHIARA,false,true,false,false,true,false,false,false,false,"Immagini/Giocatori/9.png","Hans");
    Personaggio p10 = new Personaggio(ColoriCapelli.NESSUNO,ColoriOcchi.MARRONI, ColorePelle.CHIARA,false,false,false,false,true,false,false,false,true,"Immagini/Giocatori/10.png","Herman");
    Personaggio p11 = new Personaggio(ColoriCapelli.ROSSI,ColoriOcchi.MARRONI, ColorePelle.CHIARA,false,false,false,false,false,true,false,false,false,"Immagini/Giocatori/11.png","Isabelle");
    Personaggio p12 = new Personaggio(ColoriCapelli.BIONDI,ColoriOcchi.AZZURRI, ColorePelle.CHIARA,false,false,false,false,true,false,false,false,false,"Immagini/Giocatori/12.png","Joe");
    Personaggio p13 = new Personaggio(ColoriCapelli.CASTANI,ColoriOcchi.MARRONI, ColorePelle.CHIARA,false,false,true,false,false,false,false,false,false,"Immagini/Giocatori/13.png","Katrin");
    Personaggio p14 = new Personaggio(ColoriCapelli.BIONDI,ColoriOcchi.MARRONI, ColorePelle.CHIARA,true,false,false,false,true,false,false,false,false,"Immagini/Giocatori/14.png","Lucas");
    Personaggio p15 = new Personaggio(ColoriCapelli.CASTANI,ColoriOcchi.MARRONI, ColorePelle.CHIARA,false,false,true,false,false,false,false,true,false,"Immagini/Giocatori/15.png","Marta");
    Personaggio p16 = new Personaggio(ColoriCapelli.NERI,ColoriOcchi.MARRONI, ColorePelle.SCURA,false,false,false,false,true,false,true,false,false,"Immagini/Giocatori/16.png","Max");
    Personaggio p17 = new Personaggio(ColoriCapelli.BIANCHI,ColoriOcchi.MARRONI, ColorePelle.CHIARA,true,false,false,true,true,false,false,false,false,"Immagini/Giocatori/17.png","Paul");
    Personaggio p18 = new Personaggio(ColoriCapelli.NESSUNO,ColoriOcchi.MARRONI, ColorePelle.CHIARA,false,false,false,false,true,false,true,false,true,"Immagini/Giocatori/18.png","Philippe");
    Personaggio p19 = new Personaggio(ColoriCapelli.NESSUNO,ColoriOcchi.MARRONI, ColorePelle.SCURA,true,false,false,false,true,false,false,false,true,"Immagini/Giocatori/19.png","Roger");
    Personaggio p20 = new Personaggio(ColoriCapelli.BIONDI,ColoriOcchi.MARRONI, ColorePelle.CHIARA,false,false,true,true,false,false,false,true,false,"Immagini/Giocatori/20.png","Sarah");
    Personaggio p21 = new Personaggio(ColoriCapelli.NERI,ColoriOcchi.MARRONI, ColorePelle.SCURA,false,false,false,true,false,true,false,false,false,"Immagini/Giocatori/21.png","Charles");
    Personaggio p22 = new Personaggio(ColoriCapelli.ROSSI,ColoriOcchi.AZZURRI, ColorePelle.CHIARA,false,true,false,false,true,false,false,false,false,"Immagini/Giocatori/22.png","Stephen");
    Personaggio p23 = new Personaggio(ColoriCapelli.NERI,ColoriOcchi.MARRONI, ColorePelle.CHIARA,false,true,false,false,true,false,false,false,false,"Immagini/Giocatori/23.png","Theo");
    Personaggio p24 = new Personaggio(ColoriCapelli.BIANCHI,ColoriOcchi.MARRONI, ColorePelle.CHIARA,false,false,false,false,true,false,false,false,false,"Immagini/Giocatori/24.png","Victor");
    personaggi[0] = p1;
    personaggi[1] = p2;
    personaggi[2] = p3;
    personaggi[3] = p4;
    personaggi[4] = p5;
    personaggi[5] = p6;
    personaggi[6] = p7;
    personaggi[7] = p8;
    personaggi[8] = p9;
    personaggi[9] = p10;
    personaggi[10] = p11;
    personaggi[11] = p12;
    personaggi[12] = p13;
    personaggi[13] = p14;
    personaggi[14] = p15;
    personaggi[15] = p16;
    personaggi[16] = p17;
    personaggi[17] = p18;
    personaggi[18] = p19;
    personaggi[19] = p20;
    personaggi[20] = p21;
    personaggi[21] = p22;
    personaggi[22] = p23;
    personaggi[23] = p24;
    GestorePersonaggi.Scrivi_binario(personaggi);
}